export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center bg-gradient-to-br from-neutral-900 to-zinc-800">
      <div className="w-4/5">
        <div className="py-40">
          <h1 className="text-6xl	font-mono animate-typing overflow-hidden whitespace-nowrap">Warning! Entering... ProxiViolet</h1>
          <p>Generated by LordOfTheLetter & SeekerOfUltimateFate</p>
        </div>
        <div>
          <p>
            In the realm where the digital and the arcane intertwine, ProxiViolet stands as a mysterious threshold—a gateway between the known and the enigmatic. Conceived by the enigmatic minds of
            LordOfTheLetter and SeekerOfUltimateFate, this ethereal domain is inhabited by creatures born from the twilight of cyberspace and the whispers of forgotten magic. Each entity within
            ProxiViolet carries a fragment of ancient lore, fused with the pulse of digital evolution. As you step through this portal, you embark on a journey where every click unravels a tale of
            liminal beings, suspended between reality and the fantastical. Here, the boundaries blur, and the ordinary becomes extraordinary, inviting you to explore the secrets that lie within the
            shadows of ProxiViolet.
          </p>
        </div>
      </div>
    </main>
  );
}
